defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[web]
  address = ":8080"
  [web.auth.basic]
  users = ["user:md5-password"]

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "conta@dominio"
storageFile = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dominio"
watch = true

# Para subir o container traefik:
docker network create sites
docker run -d --network sites --name traefik --restart=always -p 8080:8080 -p 80:80 -p 443:443 -v /etc/traefik/traefik.toml:/etc/traefik/traefik.toml:ro -v /etc/traefik/acme:/etc/traefik/acme -v /var/run/docker.sock:/var/run/docker.sock:ro traefik

# Para subir o container web:
docker run -d --network sites --restart=always --name site-name -e "-l traefik.backend=site-name" -e "-l traefik.frontend.rule=Host:site-name" -e "-l traefik.port=80" -v /home/site-name:/var/www/html nginx


